### ISSUE TITLE
IDLE not opening when click on OPEN in JavaScript Logging Lab

### ISSUE THREAD

**Issue by bdahiya2007** [learn-co-curriculum/javascript-logging-lab#19]
Hi,

I am trying to open IDLE by clicking on OPEN but not activity happened.

Any idea how to open it?

Thanks,
Balraj

**Comment by lbattaglioli2000** [comment]
Same issue here!

**Comment by AnnJohn** [comment]
hi @bdahiya2007 and @lbattaglioli2000 for all IDE and technical issues, please use Ask a Question and someone from our team will help you out. 

Also, could you please file a bug report? If you click on your profile pic you'll see an option to Report a Bug. Thanks!

**Comment by bdahiya2007** [comment]
Hi Luigi,

My issue got resolved. You need to install Learn IDE.

Here is the IDE Link

The link to get set up with the Learn IDE is:

https://learn.co/ide

Use your github login/handle and try again. Mine is working now.

Thanks,
Balraj

On Wed, Aug 31, 2016 at 2:46 PM, Luigi Battaglioli <notifications@github.com
