### ISSUE TITLE
The 'OPEN' button does not launch the IDE

### ISSUE THREAD

**Issue by YanKozlovskiy** [learn-co-curriculum/javascript-logging-lab#20]
I'm having this problem along with several other students. Please post the fix for this problem as soon as possible.

**Comment by AnnJohn** [comment]
hi @YanKozlovskiy this is a product issue. We use this space for issues related to curriculum content so could you file a bug report (if you click on your profile pic in Learn, you'll see an option to Report a Bug) and use Ask a Question to get immediate help from someone from our team. Thanks
