### ISSUE TITLE
Learn IDE will not open

### ISSUE THREAD

**Issue by joelvosburgh** [learn-co-curriculum/javascript-logging-lab#22]
Learn IDE will not open from blue 'open' button. what is going on?

**Comment by AnnJohn** [comment]
hi @joelvosburgh this looks like a technical, product problem. If this is still a problem, could you please use Ask a Question and someone from our team will help you out right away. thanks!

**Comment by joelvosburgh** [comment]
OK thanks 

Get Outlook for Android

On Tue, Sep 6, 2016 at 11:33 AM -0400, "AnnJohn" notifications@github.com wrote:

hi @joelvosburgh this looks like a technical, product problem. If this is still a problem, could you please use Ask a Question and someone from our team will help you out right away. thanks!
