### ISSUE TITLE
learn IDE

### ISSUE THREAD

**Issue by Countx** [learn-co-curriculum/javascript-logging-lab#26]
The learn IDE does not open , i had ask for assists but no one is available or were to busy to assist me on learn.co. Is there a issue with the IDE ?

**Comment by AnnJohn** [comment]
hi @Countx sorry for the trouble. There isn't an issue with the IDE and it most likely has something to do with set-up. Please try Ask a Question again and I will also reach out to someone to help you. Thanks!
