### ISSUE TITLE
All tests passed and "learn submit" completed but lesson isn't recognizing the pull request

### ISSUE THREAD

**Issue by dwistocki** [learn-co-curriculum/javascript-logging-lab#27]
All 3 tests from "learn test" were successful, and I ran "learn submit" to receive "Done." but Learn.co isn't recognizing that I submitted the pull request.

**Comment by AnnJohn** [comment]
hi @dwistocki could you please use Ask a Question and someone will help you troubleshoot. Also because this is a product issue, could you file a bug report instead of reporting it here. If you click on your profile pic in Learn, you'll see a menu with an option there to Report a Bug. thanks!
