### ISSUE TITLE
I am having issues passing the JavaScript Logging Lab.

### ISSUE THREAD

**Issue by mliu928** [learn-co-curriculum/javascript-logging-lab#30]
Hi, I keep getting failures when a fellow coder had helped me, I had reset basically everything that I needed to reset in order to restart the lesson, but I'm still having errors and not being able to pass all 3 requirements. Here is the error message, 

/ ♥ learn test                                                                                                                                              

> java-script-logging-lab@0.1.0 test /home/mliu928-24142/code/labs/javascript-logging-lab-bootcamp-prep-000  
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json                                                                                          

 0   __,------,  
 3   __|  /_/\  
 0   _~|_( x .x)  
     _ ""  ""  
labs\javascript-logging-lab-bootcamp-prep-000\index.js2:20
 Learn
CRLFUTF-8JavaScript

My code that I have used is, 

console.error("HALP!")
console.log('Be Careful!')
console.warn('Stop right now!')

If anyone has a solution to the problem please let me know, thanks!

**Comment by AnnJohn** [comment]
hi @mliu928 please use Ask a Question in Learn and someone will help you out right away!

Thanks
