### ISSUE TITLE
wont let me pass lab

### ISSUE THREAD

**Issue by jkaneer** [learn-co-curriculum/javascript-logging-lab#31]
i completed the lab, but seems like the program is separated from the IDE, it says passed in the IDE says two have passed in my  browser...

console.error("HALP")
console.log("BAD DUDE")
console.warn("try again")

**Comment by AnnJohn** [comment]
hi @jkaneer sorry for the delay with this but please use  Ask a Question in Learn and someone from our team will help you out right away. Thanks!
