### ISSUE TITLE
Lesson not opening on Learn IDE

### ISSUE THREAD

**Issue by amfad84** [learn-co-curriculum/javascript-logging-lab#33]
I've clicked on the open lesson button multiple times and each time it responds by looking for lesson, installing, and then opening the lesson, but the lab is never available under the drop down folder.

**Comment by AnnJohn** [comment]
hi @amfad84 sorry for the issue that you're having. Since this is a product problem, could you use Ask a Question in Learn and someone from our support team will help you troubleshoot. Thanks!
