### ISSUE TITLE
Locked Next Lesson Button

### ISSUE THREAD

**Issue by AdiyamGN** [learn-co-curriculum/javascript-logging-lab#36]
I passed all the local test. I added it to github with comment and push it. But I can't seem to pass the last stage that says "Submit pull request." when I do a poll request on the command line, I get "Already up-to-date" message. Thanks for the help.

**Comment by aturkewi** [comment]
Hey @AdiyamGN as this isn't a problem with this specific lab, it's actually a much better question for our Ask A Question button. 
Specifically though, I think you're only pushing your code up to github an _not_ submitting a pull request (that's not usually done from the command line). If you do want to manually submit a lab though, check out this help center article: https://help.learn.co/hc/en-us/articles/236395187-How-to-Manually-Submit-a-Lab

If you still need a hand, try out our Ask A Question button :)
