### ISSUE TITLE
For now, open up index.js in your text editor. If you're using the Learn IDE, click the "Open" button on this lesson

### ISSUE THREAD

**Issue by ValonRekaliu** [learn-co-curriculum/javascript-logging-lab#37]
I do not have access to IDE. I try to open several times. it does not open

**Comment by aturkewi** [comment]
This isn't exactly an issue with this specific lab, but maybe the IDE. The best place to ask this question is on Learn through the Ask A Question feature.
If the Learn Open button isn't opening up the Learn IDE for you though, take a look at this help center article: https://help.learn.co/hc/en-us/articles/230234808--Learn-open-button-issues
