### ISSUE TITLE
it dont let open de plataform to start coding

### ISSUE THREAD

**Issue by mistico27** [learn-co-curriculum/javascript-logging-lab#38]
i dont know what is going on but when i try to open the plataform to start coding it doesnt let open it it says that is a not secure site

**Comment by aturkewi** [comment]
What exactly are you clicking on to get this message? And what exactly is the message? 
Can you log into learn.co and re-ask this through the Ask A Question feature? We have Learn Experts online from 9am-1am EDT every day :)
