### ISSUE TITLE
Command : learn test, is not functioning properly on my ide

### ISSUE THREAD

**Issue by joshuadstewart91** [learn-co-curriculum/javascript-logging-lab#40]
Receiving Error- 

         from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require
.rb:133:in `rescue in require'                                                                         
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require
.rb:40:in `require'                                                                                    
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems_executable_
plugin.rb:4:in `block in <top (required)>'                                                             
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hoo
ks.rb:50:in `block in run'                                                                             
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hoo
ks.rb:49:in `each'                                                                                     
        from /usr/local/rvm/gems/ruby-2.3.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hoo
ks.rb:49:in `run'                                                                                      
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:10:in `<main>'                   
[23:09:38] javascript-logging-lab-bootcamp-prep-000                                                    
// ♥

**Comment by aturkewi** [comment]
Hey @joshuadstewart91 thanks for posting this error!
The best place to get a hand with a lab error like this though would be the Ask A Question button :) It's a bit hard for me to see what's going on without all the files in this case.
