### ISSUE TITLE
Trying to figure this out?

### ISSUE THREAD

**Issue by 1Jewellr** [learn-co-curriculum/javascript-logging-lab#41]
Hi, I am attempting the Javascript Logging Lab. When I use the 'OPEN' button to launch the Learn IDE it does not 'FORK'. I don't see the files referenced in the lesson instructions. I have attempted to find a post or guide to help troubleshoot the issue. I am at a loss for solutions to try. Has anyone had this problem? And any guidance towards resources to help solve?

**Comment by aturkewi** [comment]
Hey @1Jewellr this doesn't exactly sound like an issue with this lab, but perhaps maybe with some account issues. 
The best place to ask a question like this would be through our Ask A Question feature on Learn or using the Report A Bug feature on Learn.
