### ISSUE TITLE
trying to run the test but it keeps giving this error(You don't appear to be in a Learn lesson's directory. Please cd to an appropriate directory and try a gain.)

### ISSUE THREAD

**Issue by mikelafalce** [learn-co-curriculum/javascript-logging-lab#42]
I have tried restarting learn and i keep getting this error when i run 'learn test'.

**Comment by aturkewi** [comment]
Hey @mikelafalce this kind of questions is really better for our Ask A Question feature in Learn as this isn't really an issue with the lab. 
For this specific question though, I think this help center article is what you're looking for :) https://help.learn.co/hc/en-us/articles/230089227-You-don-t-appear-to-be-in-a-Learn-lesson-s-directory
