### ISSUE TITLE
Javascript logging test

### ISSUE THREAD

**Issue by poida84** [learn-co-curriculum/javascript-logging-lab#45]
I am unsure where to put the console.error("Help!")

I have tried at the start, under the it statement and my first wont pass

**Comment by aturkewi** [comment]
Hey @poida84 this is a great question for the Ask A Question feature :)

This Issues sections is if the lab appears to be broken. As far as I know, this lab is working properly. If you need a hand with it though, please feel free to use the Ask A Question feature in Learn and we'll be happy to lend a hand there.
