### ISSUE TITLE
Console.error ("FAILING WAH!")

### ISSUE THREAD

**Issue by mwimberl2** [learn-co-curriculum/javascript-logging-lab#60]
In index.js I am trying to add a call to my function console.error().  The test description says, "index calls console.error()". So I tried to add a call to my code:

Index-test.js I added..
  it('calls console.error("HALP!")'

However, I am still 0-3 failing. Am I missing a step somewhere in my thought process?

Meryl

**Comment by evalljam12** [comment]
I am having the same problem!

**Comment by LShybrid1980** [comment]
same here

**Comment by Mnelson1992** [comment]
I am having the same issue. Anyone figure out a solution?

**Comment by gj** [comment]
Hi @mwimberl2, @evalljam12, @LShybrid1980, and @Mnelson1992!

We added a note about not editing the test file: 77658d826585bb264d8737596b7a4faa82a7779b

Thanks!
