### ISSUE TITLE
Not defined

### ISSUE THREAD

**Issue by mikhailalloy** [learn-co-curriculum/javascript-logging-lab#61]
Here is my code:

function basicTeenager(age) { if (13 <= age && age <= 19)
  {return "You are a teenager"}
}

function teenager(age) {if (13 <= age && age <= 19)
  {return "You are a teenager"}
else {return "You are not a teenager"}
}

function ageChecker(age) {if (13 <= age && age <= 19)
  {return "You are a teenager"}
else if (age<13) {return "You are a kid"}
else {return "You are a grownup"}
}

function ternaryTeenager(age) {return (13 <= age && age <= 19)? "You are a teenager" : "You are not a teenager"

}

function switchAge(age) {case (13 <= age && age <= 19):
  return "You are a teenager"
  break;
  default:
  return "You have an age"

}

when I run it (via learn test)

I get 11 failing tests and 11  error messages saying functions are not defined, which doesnt make sense because the definitions are right in the code

Example: 

  1) flow-control basicTeenager should return "You are a teenager!" if the age is between 13-19
:                                                                                              
     ReferenceError: basicTeenager is not defined                                              
      at Context.it (test/flow-control-test.js:26:14)

**Comment by blakejoy** [comment]
Same thing happened to me

**Comment by gj** [comment]
Hi there!

It looks like you may have raised this issue on the wrong repository. In addition, this seems like it would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 🙂
