### ISSUE TITLE
Talk about workflow in debugging

### ISSUE THREAD

**Issue by JeffKatzy** [learn-co-curriculum/javascript-logging-lab#8]
Add in a debugger, open the console, etc.

Might also be good to have a section on google dev tools, etc.

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by pletcher** [comment]
We actually have a lesson this later -- I think we can move it earlier.

**Comment by pletcher** [comment]
The normal debugging flow won't work for this lab. Students haven't learned about functions yet, so we're really really restricted in how we can do this.
